2020 update
conveyal/osm-lib pull request #37
Opened 2020-07-18 21:04 UTC by evansiroky

- update to latest osmosis library
- fix javax import
- fix error causing NPE when a network failure occurs while updating
- fix error caused by not catching URL parsing error

2020-07-20 17:32 UTC, landonreed commented on src/main/java/com/conveyal/osmlib/Updater.java
> +            String replicationUrl = sb.toString();
Can we call this `planetReplicationUrl`?

2020-07-20 17:35 UTC, landonreed commented on src/main/java/com/conveyal/osmlib/VanillaExtract.java
> +                    throw new IllegalArgumentException("Must provide a bounding box with 4 coordinates");
This exception should probably be thrown, but there is a TODO in the code below that talks about future work on an extra `buildings` param. Maybe that should just be removed for now?

2020-07-20 17:38 UTC, landonreed commented on src/main/java/com/conveyal/osmlib/VanillaExtract.java
> -                ex.printStackTrace();
Do we not want to print the exception at all? I think we should maybe have separate catch clauses. One for generic exception that prints the exception and one for the IllegalArgumentException, that just prints the error message with URI above.

2020-07-20 17:39 UTC, landonreed requested changes
Looks good. Just one blocking change with respect to the catch clause

2020-07-21 23:04 UTC, evansiroky commented
Changes should be addressed

2020-07-22 13:53 UTC, landonreed approved these changes

2020-07-22 13:54 UTC, merged